language: python

python:
  - 3.7

services:
  - mysql

cache: pip

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS main;'

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: "Tests"
      name: "Master Pi Tests"
      script: ./build.sh 1
    - name: "Agent Pi Tests"
      script: ./build.sh 2
